### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by DAP52113** [SiyuLou/AutomaticHeartSoundClassification#2]
您好，博主，我运行了您的代码，环境都调试完成了，但出现了一个报错，
`Trainable parameters: 3805152
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    main(config)
  File "train.py", line 73, in main
    trainer.train()
  File "/hy-tmp/AutomaticHeartSoundClassification/base/base_trainer.py", line 63, in train
    result = self._train_epoch(epoch)
  File "/hy-tmp/AutomaticHeartSoundClassification/trainer/trainer.py", line 44, in _train_epoch
    for batch_idx, (data, target) in enumerate(self.data_loader):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 229, in __iter__
    for idx in self.sampler:
  File "/hy-tmp/AutomaticHeartSoundClassification/data_loader/data_loaders.py", line 111, in __iter__
    self._resample()
  File "/hy-tmp/AutomaticHeartSoundClassification/data_loader/data_loaders.py", line 107, in _resample
    random_idxs = np.random.randint(leng, size=leftover)
  File "mtrand.pyx", line 747, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1254, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high`

我 的数据集就是官网的心音数据集，然后把a-f全部的wav文件放在一个文件夹里面，然后设置了一个label.csv文件
还是报错

**Comment by SiyuLou** [comment]
您好， 请问你有提取特征吗？特征提取请见utils/audio_feature_extractor.py

**Comment by qizhiJing** [comment]
> 您好，请问您有提取特征吗？提取请见utils/audio_feature_extractor.py

您好，我也是这个问题 做过特征提取了

**Comment by qizhiJing** [comment]
> 您好，请问您有提取特征吗？提取请参见utils/audio_feature_extractor.py

您好，我也是这个问题 做过特征提取了

**Comment by qizhiJing** [comment]
> 您好，请问您提取了特征吗？提取请参见utils/audio_feature_extractor.py

您好 我也是这个问题 提取过特征了

**Comment by zhangwenjun1229** [comment]
> 您好，博主，我运行了您的代码，环境都调试完成了，但出现了一个报错， `Trainable parameters: 3805152 Traceback (most recent call last): File "train.py", line 92, in <module> main(config) File "train.py", line 73, in main trainer.train() File "/hy-tmp/AutomaticHeartSoundClassification/base/base_trainer.py", line 63, in train result = self._train_epoch(epoch) File "/hy-tmp/AutomaticHeartSoundClassification/trainer/trainer.py", line 44, in _train_epoch for batch_idx, (data, target) in enumerate(self.data_loader): File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 359, in __iter__ return self._get_iterator() File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator return _MultiProcessingDataLoaderIter(self) File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 944, in __init__ self._reset(loader, first_iter=True) File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 975, in _reset self._try_put_index() File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index index = self._next_index() File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 512, in _next_index return next(self._sampler_iter) # may raise StopIteration File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 229, in __iter__ for idx in self.sampler: File "/hy-tmp/AutomaticHeartSoundClassification/data_loader/data_loaders.py", line 111, in __iter__ self._resample() File "/hy-tmp/AutomaticHeartSoundClassification/data_loader/data_loaders.py", line 107, in _resample random_idxs = np.random.randint(leng, size=leftover) File "mtrand.pyx", line 747, in numpy.random.mtrand.RandomState.randint File "_bounded_integers.pyx", line 1254, in numpy.random._bounded_integers._rand_int64 ValueError: low >= high`
> 
> 我 的数据集就是官网的心音数据集，然后把a-f全部的wav文件放在一个文件夹里面，然后设置了一个label.csv文件 还是报错

你的label是不是原始数据的-1，1。在data_loader 的class MinimumOccupancySampler(Sampler) __init__中，label处理方式可以看到是0，1的。所以如果你是-1的label就没办法匹配到index，导致提取数据的时候leng=0，从而random报错。
